-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS material_type;

DROP TABLE IF EXISTS product_type CASCADE;

DROP TABLE IF EXISTS partners CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS partner_products CASCADE;

DROP TYPE IF EXISTS organization_type CASCADE;

CREATE TYPE public.organization_type AS ENUM ('ЗАО', 'ОАО', 'ООО', 'ПАО');

CREATE TABLE
    public.material_type (
        id bigserial NOT NULL,
        name character varying(100) COLLATE pg_catalog."default" NOT NULL,
        defect_rate double precision NOT NULL,
        CONSTRAINT material_type_pkey PRIMARY KEY (id)
    );

CREATE TABLE
    public.partner_products (
        id bigserial NOT NULL,
        product_id bigint NOT NULL,
        partner_id bigint NOT NULL,
        product_quantity bigint NOT NULL,
        sell_date date NOT NULL,
        CONSTRAINT partner_products_pkey PRIMARY KEY (id)
    );

CREATE TABLE
    public.partners (
        id bigserial NOT NULL,
        name character varying(100) COLLATE pg_catalog."default" NOT NULL,
        type organization_type NOT NULL,
        email character varying(100) COLLATE pg_catalog."default" NOT NULL,
        phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
        address text COLLATE pg_catalog."default" NOT NULL,
        tin bigint NOT NULL,
        rating smallint NOT NULL,
        director character varying(100) COLLATE pg_catalog."default" NOT NULL,
        CONSTRAINT partners_pkey PRIMARY KEY (id)
    );

CREATE TABLE
    public.product_type (
        id bigserial NOT NULL,
        name text COLLATE pg_catalog."default" NOT NULL,
        ratio double precision NOT NULL,
        CONSTRAINT product_type_pkey PRIMARY KEY (id)
    );

CREATE TABLE
    public.products (
        id bigserial NOT NULL,
        name text COLLATE pg_catalog."default" NOT NULL,
        product_type_id bigint NOT NULL,
        article bigint NOT NULL,
        min_price double precision NOT NULL,
        CONSTRAINT products_pkey PRIMARY KEY (id)
    );

ALTER TABLE IF EXISTS public.partner_products
ADD CONSTRAINT partner_products_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.partner_products
ADD CONSTRAINT partner_products_produckt_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

ALTER TABLE IF EXISTS public.products
ADD CONSTRAINT product_type_id FOREIGN KEY (product_type_id) REFERENCES public.product_type (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

END;